Running in parallel on 20 cores
current state: start

  0%|          | 0/37 [00:00<?, ?it/s]
100%|██████████| 37/37 [00:00<00:00, 4900.35it/s]
current state: mode_solving
0 108563286 5868968
0 108563286 5868963
0 108563286 5868798
0 108563286 5868758
0 108563286 5868598
0 108563286 5868543
0 108563286 5868398
0 108563286 5868373
0 108563286 5868303
0 108563286 5868178
0 108563286 5868044
0 108563286 5867949
0 108563286 5867859
0 108563286 5867774
0 108563286 5867619
0 108563286 5867584
0 108563286 5867321
0 108563286 2934527
0 108563286 2934392
0 108563286 2934337

0it [00:00, ?it/s]
1it [00:29, 29.44s/it]
2it [01:24, 44.55s/it]
2it [01:24, 42.28s/it]
current state: finished_modes
current state: layer_propagating
0 4355817060 187921599
0 4355817060 187660109
0 4355817060 187631744
0 4355817060 194830212
0 4355817060 202040503
0 4355817060 209250065
0 4355817060 216451916
0 4355817060 216540171
0 4355817060 231183191
0 4355817060 245774638
0 4355817060 260310166
0 4355817060 282098804
0 4355817060 289184612
0 4355817060 288974172
0 4355817060 289099442
0 4355817060 289025872
0 4355817060 144245531
0 4355817060 144450011
0 4355817060 144522521
0 4355817060 144621781
Traceback (most recent call last):
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "adiabatic.py", line 79, in <module>
    eme.propagate()
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 599, in propagate
    self.propagate_layers()
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 212, in propagate_layers
    results = self._run_parallel_functions(*tasks)
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 697, in _run_parallel_functions
    data = self.batch_scatter(data, root=0)
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 637, in batch_scatter
    scattered.append(self.comm.scatter(to_scatter, root=root))
  File "mpi4py/MPI/Comm.pyx", line 1587, in mpi4py.MPI.Comm.scatter
  File "mpi4py/MPI/msgpickle.pxi", line 823, in mpi4py.MPI.PyMPI_scatter
  File "mpi4py/MPI/msgpickle.pxi", line 167, in mpi4py.MPI.pickle_dumpv
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 2339594413 does not fit in 'int'
