Running in parallel on 20 cores
current state: start
size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


  0%|          | 0/37 [00:00<?, ?it/s]100%|██████████| 37/37 [00:00<00:00, 4639.16it/s]
size:  2 


size:  2 


current state: mode_solving
size:  108553565 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


0it [00:00, ?it/s]1it [00:32, 32.76s/it]2it [01:27, 45.41s/it]2it [01:27, 43.51s/it]
size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


size:  2 


current state: finished_modes
current state: layer_propagating
size:  2224930877 


Traceback (most recent call last):
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/fslhome/ihammond/.local/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/fslhome/ihammond/miniconda3/envs/emepy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "adiabatic.py", line 79, in <module>
    eme.propagate()
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 598, in propagate
    self.propagate_layers()
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 211, in propagate_layers
    results = self._run_parallel_functions(*tasks)
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 662, in _run_parallel_functions
    data = self.batch_scatter(data, root=0)
  File "/zhome/ihammond/GitHub/emepy/emepy/eme.py", line 616, in batch_scatter
    return self.comm.scatter(data, root=root)
  File "mpi4py/MPI/Comm.pyx", line 1587, in mpi4py.MPI.Comm.scatter
  File "mpi4py/MPI/msgpickle.pxi", line 823, in mpi4py.MPI.PyMPI_scatter
  File "mpi4py/MPI/msgpickle.pxi", line 167, in mpi4py.MPI.pickle_dumpv
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 2247451655 does not fit in 'int'
